name: Delete Untagged Images

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Get all package names
        id: packages
        run: |
          PACKAGES=$(find images -maxdepth 1 -type d -not -path images | paste -sd ',' -)
          echo "packages=$PACKAGES" >> "$GITHUB_OUTPUT"
          echo "Found packages: $PACKAGES"

      - name: Clean up packages
        uses: dataaxiom/ghcr-cleanup-action@34a2b6c814b9c6bcb92f78cba3e56a7ab9ca7a86 # v1
        with:
          packages: ${{ steps.packages.outputs.packages }}
          delete-untagged: true
          older-than: 3 months
          keep-n-tagged: 10
          validate: true
